### ISSUE TITLE
Checkpoints of pre-trained models for finetuning

### ISSUE THREAD

**Issue by crlna16** [AWF-GAUG/TreeCrownDelineation#15]
This is a very useful repository!

We would like to fine tune the pretrained models on our own dataset. If you are able to, could you please provide training checkpoints of your pretrained models with 20 cm resolution? That would be greatly appreciated.

**Comment by maxfreu** [comment]
Thanks! :)

We never trained a model on 20cm images, only on 30cm WorldView-3 and 5cm aerial. As postet on the main page, you can download the models here: https://owncloud.gwdg.de/index.php/s/9cUza134XSOwZsB

If you have 20cm aerial images with 4 bands, you can just use the 5cm model and continue training with that. But I think I have a model trained on 20cm 4 band images flying around somewhere... maybe I can upload those weights as well, but not before October.

**Comment by crlna16** [comment]
Our assumption was that the model in tcd-20cm-RGBI-v1.0.zip is trained on 20cm resolution data according to the readme, are we on the wrong path here?

We were also wondering if you could provide pytorch checkpoints that would allow us to resume training (we want to fine tune on a much smaller dataset). Did you by any chance save them during training? The *.pt models can be used for inference only as far as I know

**Comment by maxfreu** [comment]
Sorry, my bad. The readme is correct and the published model was indeed trained on 20cm 4 band aerial images.

You don't need my checkpoints for finetuning. You can load the published just in time compiled model; it contains the model definition and the weights - that's all you need. The optimizer state etc. that is sometimes stored in a checkpoint is only needed if you want to resume training from exactly the same point on the same dataset.
