### ISSUE TITLE
AttributeError: Can't get attribute 'work' on <module '__mp_main__' 

### ISSUE THREAD

**Issue by Coder-GAN** [AWF-GAUG/TreeCrownDelineation#2]
Hi there,
I very much appreciate your work and I want to use your methods in my topic. But I faced an error when I used the functions provided by the scripts, I tried to fix the error but none of the solutions worked. 

Here is my code : python clip_image.py -i C:/Users/Gan/ITCD/0518.tif -o C:/Users/Gan/ITCD/data/tiles/tile_ -shp C:/Users/Gan/ITCD/border.shp

Input raster files:  1
C:\Users\Gan\ITCD\TreeCrownDelineation\scripts\clip_image.py:243: DeprecationWarning: open_rasterio is Deprecated in favor of rioxarray. For information about transitioning, see: https://corteva.github.io/rioxarray/stable/getting_started/getting_started.html
  source_raster = xr.open_rasterio(file_, "r", lock=readlock, cache=False)
Feature count: 1
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "C:\Users\Gan\.conda\envs\ITCD\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Gan\.conda\envs\ITCD\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Gan\.conda\envs\ITCD\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\Gan\.conda\envs\ITCD\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'work' on <module '__mp_main__' from 'C:\\Users\\Gan\\ITCD\\TreeCrownDelineation\\scripts\\clip_image.py'>

**Comment by maxfreu** [comment]
I mark this as resolved after email conversation. If the issue still persists, feel free to reopen.

**Comment by JPPereira93** [comment]
hello! i'm getting this error when running :

python "C:\Users\fuji_\Desktop\WFS_CTAPP\Tree_Segmentation\TreeCrownDelineation\scripts\rasterize.py" -i "D:\World_From_Space\CTAPP\Internal_outputs\Tree_segmentation\Hradec_Kralove\Folder_Structure\data\tiles\Hradec_Kralove_orthoimagery_merged_5514_part_3.tif" -o "D:\World_From_Space\CTAPP\Internal_outputs\Tree_segmentation\Hradec_Kralove\Folder_Structure\data\mask\mask_" -shp "D:\World_From_Space\CTAPP\Internal_outputs\Tree_segmentation\Hradec_Kralove\Training_Samples\sample_segments_hrka_5514_tile_3.geojson"

if you could help me solve this id appreciate it very much!

EDIT: Im working on windows 11 OS and i also couldnt install the .yml env

**Comment by maxfreu** [comment]
Dear @JPPereira93, please open a new issue for this. So far, you have also only written what you tried to run, but to help, I need the error message ("stack trace").
